const SKILLS_DB = {
  languages: [
    { name: "Python", aliases: ["python3", "py"] },
    { name: "Java", aliases: ["java8", "java11", "java17", "java 8", "java 11", "java 17"] },
    { name: "JavaScript", aliases: ["js", "es6", "es2015", "ecmascript", "vanilla js"] },
    { name: "TypeScript", aliases: ["ts"] },
    { name: "C++", aliases: ["cpp", "c plus plus", "cplusplus"] },
    { name: "C", aliases: ["c language", "c programming"] },
    { name: "C#", aliases: ["csharp", "c sharp", "dotnet c#"] },
    { name: "Go", aliases: ["golang", "go lang"] },
    { name: "Rust", aliases: ["rust lang"] },
    { name: "Ruby", aliases: ["ruby on rails", "ror"] },
    { name: "PHP", aliases: ["php7", "php8"] },
    { name: "Swift", aliases: ["swift ui"] },
    { name: "Kotlin", aliases: ["kotlin android"] },
    { name: "Scala", aliases: ["scala lang"] },
    { name: "R", aliases: ["r language", "r programming"] },
    { name: "Fortran", aliases: ["fortran 90", "fortran 95"] },
    { name: "MATLAB", aliases: ["matlab programming"] },
    { name: "Bash", aliases: ["bash scripting", "shell scripting", "unix shell", "shell script"] },
    { name: "PowerShell", aliases: ["powershell scripting"] },
    { name: "Perl", aliases: [] },
    { name: "Hack", aliases: ["hack lang"] },
  ],

  webFrameworks: [
    { name: "React", aliases: ["reactjs", "react.js", "react js"] },
    { name: "Angular", aliases: ["angularjs", "angular.js", "angular 2", "angular js"] },
    { name: "Vue.js", aliases: ["vuejs", "vue js", "vue"] },
    { name: "Node.js", aliases: ["nodejs", "node js"] },
    { name: "Express", aliases: ["expressjs", "express.js"] },
    { name: "Spring Boot", aliases: ["springboot", "spring-boot", "spring framework", "spring mvc"] },
    { name: "Django", aliases: ["django rest", "drf"] },
    { name: "FastAPI", aliases: ["fast api"] },
    { name: "Flask", aliases: ["flask python"] },
    { name: "Next.js", aliases: ["nextjs", "next js"] },
    { name: "NestJS", aliases: ["nestjs"] },
    { name: "Laravel", aliases: [] },
    { name: "ASP.NET", aliases: ["asp.net core", "asp net", "aspnetcore"] },
    { name: ".NET", aliases: ["dotnet", "dot net", ".net core", ".net framework"] },
    { name: "jQuery", aliases: ["jquery"] },
    { name: "GraphQL", aliases: ["graph ql"] },
    { name: "gRPC", aliases: ["grpc", "grpc api"] },
    { name: "REST API", aliases: ["restful api", "rest", "restful", "api development"] },
  ],

  databases: [
    { name: "MySQL", aliases: ["mysql server"] },
    { name: "PostgreSQL", aliases: ["postgres", "pg"] },
    { name: "MongoDB", aliases: ["mongo", "mongodb atlas"] },
    { name: "Redis", aliases: ["redis cache"] },
    { name: "Elasticsearch", aliases: ["elastic search", "elastic", "elk"] },
    { name: "SQL Server", aliases: ["microsoft sql server", "mssql", "ms sql"] },
    { name: "SQLite", aliases: ["sqlite3"] },
    { name: "Cassandra", aliases: ["apache cassandra"] },
    { name: "DynamoDB", aliases: ["aws dynamodb"] },
    { name: "Oracle DB", aliases: ["oracle database", "oracle"] },
    { name: "DB2", aliases: ["ibm db2"] },
    { name: "SQL", aliases: ["structured query language", "t-sql", "pl/sql"] },
    { name: "NoSQL", aliases: ["no sql", "no-sql"] },
  ],

  cloudDevOps: [
    { name: "AWS", aliases: ["amazon web services", "amazon aws", "aws cloud"] },
    { name: "Azure", aliases: ["microsoft azure", "azure cloud"] },
    { name: "GCP", aliases: ["google cloud", "google cloud platform", "google cloud services"] },
    { name: "Docker", aliases: ["docker container", "containerization"] },
    { name: "Kubernetes", aliases: ["k8s", "kubectl", "kube"] },
    { name: "Jenkins", aliases: ["jenkins ci", "jenkins pipeline"] },
    { name: "Terraform", aliases: ["terraform iac"] },
    { name: "Ansible", aliases: ["ansible automation"] },
    { name: "Chef", aliases: ["chef automation"] },
    { name: "CI/CD", aliases: ["cicd", "continuous integration", "continuous deployment", "continuous delivery"] },
    { name: "GitLab CI", aliases: ["gitlab ci/cd", "gitlab pipeline"] },
    { name: "GitHub Actions", aliases: ["github action"] },
    { name: "Helm", aliases: ["helm chart"] },
  ],

  aiMl: [
    { name: "Machine Learning", aliases: ["ml", "machine learning algorithms"] },
    { name: "Deep Learning", aliases: ["neural network", "neural networks", "dl"] },
    { name: "AI", aliases: ["artificial intelligence", "ai/ml"] },
    { name: "PyTorch", aliases: ["pytorch"] },
    { name: "TensorFlow", aliases: ["tensorflow", "tf"] },
    { name: "scikit-learn", aliases: ["sklearn", "scikit learn"] },
    { name: "NLP", aliases: ["natural language processing", "natural language"] },
    { name: "Computer Vision", aliases: ["cv", "image processing"] },
    { name: "Pandas", aliases: ["pandas dataframe"] },
    { name: "NumPy", aliases: ["numpy"] },
    { name: "Spark", aliases: ["apache spark", "pyspark"] },
  ],

  toolsVersionControl: [
    { name: "Git", aliases: ["github", "bitbucket", "git version control"] },
    { name: "SVN", aliases: ["subversion"] },
    { name: "ClearCase", aliases: ["ibm clearcase"] },
    { name: "JIRA", aliases: ["jira board"] },
    { name: "Confluence", aliases: [] },
    { name: "ELK Stack", aliases: ["elk", "kibana", "logstash", "elasticsearch kibana logstash"] },
    { name: "Kibana", aliases: [] },
    { name: "Grafana", aliases: [] },
    { name: "Prometheus", aliases: [] },
    { name: "Kafka", aliases: ["apache kafka"] },
    { name: "RabbitMQ", aliases: ["rabbit mq"] },
    { name: "ActiveMQ", aliases: ["active mq"] },
    { name: "Nginx", aliases: ["nginx server"] },
    { name: "Linux", aliases: ["linux os", "ubuntu", "centos", "unix", "unix-like"] },
  ],

  concepts: [
    { name: "Microservices", aliases: ["microservice architecture", "micro services"] },
    { name: "Agile", aliases: ["agile methodology", "agile development"] },
    { name: "Scrum", aliases: ["scrum methodology"] },
    { name: "SDLC", aliases: ["software development lifecycle", "software development life cycle"] },
    { name: "TDD", aliases: ["test-driven development", "test driven development"] },
    { name: "OOP", aliases: ["object oriented programming", "object-oriented", "oop concepts"] },
    { name: "Design Patterns", aliases: ["design pattern"] },
    { name: "Unit Testing", aliases: ["unit test", "unit tests"] },
    { name: "HPC", aliases: ["high performance computing", "high-performance computing"] },
    { name: "MPI", aliases: ["message passing interface"] },
    { name: "OpenMP", aliases: ["open mp"] },
    { name: "RTOS", aliases: ["real-time operating system", "real time os"] },
    { name: "FPGA", aliases: [] },
    { name: "Embedded Systems", aliases: ["embedded programming", "embedded software"] },
    { name: "DevSecOps", aliases: ["devsecops"] },
    { name: "DevOps", aliases: ["dev ops"] },
    { name: "Full Stack", aliases: ["fullstack", "full-stack"] },
    { name: "UI/UX", aliases: ["ui design", "ux design", "user interface", "user experience"] },
    { name: "System Design", aliases: ["system architecture", "software architecture"] },
    { name: "Data Structures", aliases: ["data structure and algorithms", "dsa"] },
    { name: "Algorithms", aliases: ["algorithm design"] },
    { name: "Security Clearance", aliases: ["ts/sci", "secret clearance", "top secret", "polygraph", "poly"] },
    { name: "Cloud Native", aliases: ["cloud-native", "cloud native development"] },
    { name: "Protobuf", aliases: ["protocol buffers", "proto buffer"] },
    { name: "YAML", aliases: ["yml"] },
    { name: "JSON", aliases: ["json format"] },
    { name: "TypeScript", aliases: ["ts"] },
    { name: "CSS", aliases: ["css3", "cascading style sheets"] },
    { name: "HTML", aliases: ["html5"] },
    { name: "WebSocket", aliases: ["websockets"] },
  ],

  specialized: [
    { name: "C#/.NET", aliases: [] },
    { name: "AngularJS", aliases: ["angular js"] },
    { name: "ReactJS", aliases: ["react.js"] },
    { name: "Spring", aliases: ["spring framework"] },
    { name: "Hibernate", aliases: [] },
    { name: "Maven", aliases: [] },
    { name: "Gradle", aliases: [] },
    { name: "gRPC", aliases: ["grpc"] },
    { name: "Protobuf", aliases: ["protocol buffer"] },
    { name: "OpenAPI", aliases: ["swagger", "openapi"] },
    { name: "WebAssembly", aliases: ["wasm"] },
    { name: "ElasticSearch", aliases: ["elastic search"] },
    { name: "Kibana", aliases: [] },
    { name: "Logstash", aliases: [] },
    { name: "Prometheus", aliases: [] },
    { name: "Grafana", aliases: [] },
    { name: "Airflow", aliases: ["apache airflow"] },
    { name: "Hadoop", aliases: ["apache hadoop", "hdfs"] },
    { name: "Databricks", aliases: [] },
    { name: "Snowflake", aliases: [] },
    { name: "Core Java", aliases: ["core java programming"] },
    { name: "Python", aliases: [] },
    { name: "Django REST", aliases: ["django rest framework"] },
    { name: "PostgreSQL", aliases: ["postgres"] },
    { name: "Docker Swarm", aliases: [] },
    { name: "AWS Lambda", aliases: ["lambda", "serverless"] },
    { name: "EC2", aliases: ["aws ec2"] },
    { name: "S3", aliases: ["aws s3"] },
    { name: "GPU Programming", aliases: ["cuda", "opencl"] },
    { name: "PyTorch", aliases: [] },
  ],
};

function getAllSkills() {
  const all = [];
  for (const category of Object.values(SKILLS_DB)) {
    for (const skill of category) {
      all.push(skill);
    }
  }
  const seen = new Set();
  return all.filter((s) => {
    const key = s.name.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

module.exports = { SKILLS_DB, getAllSkills };
